name: Scala CI

on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        scala: [2.13.13, 2.12.18, 2.11.12]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache SBT dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/build.properties', 'project/plugins.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
          
    - name: Check code formatting
      run: sbt scalafmtCheckAll
      
    - name: Compile code
      run: sbt compile
      
    - name: Run tests
      run: sbt test
      
    - name: Generate coverage report
      run: sbt coverage test coverageReport || true
